#!/bin/bash
echo "enable dual"
#export XAUTHORITY=/home/zipeldiablo/.Xauthority
#export DISPLAY=:0

xrandr \
     --output HDMI2 --mode "3440x1440" --rate 60 --left-of HDMI1\
     --output HDMI2 --primary
