#!/bin/bash

VM=$1
MODE=$2
STATE=$3

echo "Call hooks: $1 $2 $3" >> /home/zipeldiablo/hooks.log

if [ "$2" == "prepare" ] && [ "$3" == "begin" ] ; then
   /home/zipeldiablo/sbin/hookVmPrepare $1 >> /home/zipeldiablo/hooks.log 2>&1
   if [ ! $? -eq 0 ] ; then
      exit 1
   fi
elif [ "$2" == "start" ] && [ "$3" == "begin" ] ; then
   /home/zipeldiablo/sbin/hookVmStart $1 >> /home/zipeldiablo/hooks.log 2>&1
   if [ ! $? -eq 0 ] ; then
      exit 1
   fi
elif [ "$2" == "started" ] && [ "$3" == "begin" ] ; then
   /home/zipeldiablo/sbin/hookVmStarted $1 >> /home/zipeldiablo/hooks.log 2>&1
   if [ ! $? -eq 0 ] ; then
      exit 1
   fi
elif [ "$2" == "stopped" ] && [ "$3" == "end" ] ; then
   /home/zipeldiablo/sbin/hookVmStopped $1 >> /home/zipeldiablo/hooks.log 2>&1
elif [ "$2" == "release" ] && [ "$3" == "end" ]  ; then
   /home/zipeldiablo/sbin/hookVmRelease $1 >> /home/zipeldiablo/hooks.log 2>&1
fi
